name: drupal-scaffold
recipe: drupal8

config:
  php: "7.2"
  webroot: web
  xdebug: true

events:
  # Clear cache after a database import
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cache-rebuild --yes

services:
  appserver:
    run:
      - cd $LANDO_MOUNT && composer install

  nodejs:
    type: node:10
    globals:
      gulp-cli: latest
    run:
      - cd $LANDO_MOUNT && npm install
      - cd $LANDO_MOUNT && gulp build

  phpmyadmin:
    type: phpmyadmin

tooling:
  gulp:
    service: nodejs
  node:
    service: nodejs
  npm:
    service: nodejs
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
  phpcs:
    service: appserver
    cmd: vendor/bin/phpcs
