name: drupal-scaffold
recipe: drupal9

config:
  php: "7.3"
  webroot: docroot
  xdebug: false
  database: mariadb:10.3

events:
  # Clear cache after a database import
  post-db-import:
    - appserver: cd $LANDO_WEBROOT && drush cache-rebuild --yes

services:
  appserver:
    run:
      - cd $LANDO_MOUNT && composer install

  nodejs:
    type: node:10
    globals:
      gulp-cli: latest
    run:
      - cd $LANDO_MOUNT && npm install
      - cd $LANDO_MOUNT && gulp build

  phpmyadmin:
    type: phpmyadmin

tooling:
  gulp:
    service: nodejs
  node:
    service: nodejs
  npm:
    service: nodejs
  phpunit:
    service: appserver
    cmd: vendor/bin/phpunit
  phpcs:
    service: appserver
    cmd: vendor/bin/phpcs
  security-check:
    service: appserver
    cmd: "php vendor/sensiolabs/security-checker/security-checker security:check composer.lock"
